eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 271024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  application:
    name: Registration-Service

resilience4j:
  circuitbreaker:
    instances:
      registrationIdEvent:
        enabled: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      registrationIdEvent:
        maxAttempts: 3
        waitDuration: 4s

  ratelimiter:
    instances:
      registrationRateLimiter:
        limitRefreshPeriod: 10s
        limitForPeriod: 2
        timeoutDuration: 5s


management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always